### ISSUE TITLE
Support for serialization and memory mapping?

### ISSUE THREAD

**Issue by pombredanne** [daac-tools/daachorse#24]
Hi:
I wonder if this library support serialization of an automaton to disk? And if so, does it support memory mapping such file?

**Comment by vbkaisetsu** [comment]
> I wonder if this library support serialization of an automaton to disk?

Serialization and deserialization are supported in v0.4.1.
Deserialization is *unsafe* because it does not verify the given data.

https://docs.rs/daachorse/latest/daachorse/struct.DoubleArrayAhoCorasick.html#method.deserialize_from_slice_unchecked

> And if so, does it support memory mapping such file?

No, it does not support memory mapping.

**Comment by pombredanne** [comment]
Dear Koichi Akabe-san!
Thank you++ for the quick response
